#!/home/gisikw/.nvm/versions/node/v6.7.0/bin/node
var pm2 = require('pm2')
pm2.connect(() => {
  pm2.list((err, data) => {
    pm2.sendDataToProcessId(data[Object.keys(data)[0]].pm2_env.pm_id, {
      topic: 'msg',
      data: process.argv.slice(2).join(' '),
    });
    pm2.disconnect(() => {});
  });
});
